import type {
  Phase4CompanyCategory,
  Phase4CompanyReference,
  Phase4RequiredAction,
  Phase4TaskTag,
} from "../types/phase4.types";

const company = (
  companyId: string,
  displayName: string,
  primaryCategory: Phase4CompanyCategory,
  keywordsEn: string[],
  keywordsFi: string[],
  actionHints: Phase4RequiredAction[],
  tagHints: Phase4TaskTag[] = ["Quality"],
  isDefaultForCategory = false,
  workIntents: string[] = [],
  responsibilitySummary?: { en: string; fi: string },
): Phase4CompanyReference => ({
  companyId,
  displayName,
  primaryCategory,
  responsibilitySummary,
  workIntents,
  roleLabels: { en: [primaryCategory.replace(/_/g, " ")], fi: [primaryCategory.replace(/_/g, " ")] },
  serviceKeywords: { en: keywordsEn, fi: keywordsFi },
  actionHints: { en: actionHints, fi: actionHints },
  tagHints,
  isDefaultForCategory,
});

export const PHASE4_DUMMY_COMPANIES_V1: readonly Phase4CompanyReference[] = [
  company("company_aquapipe_finland", "AquaPipe Finland Oy", "plumbing", ["pipe", "leak", "water leak", "plumbing", "gas connection", "gas pipe", "gas line", "pipe connection"], ["putki", "vesivuoto", "vuoto", "lvi", "kaasuliitäntä", "kaasuputki"], ["Korjaus", "Fixed"], ["Quality"], true, ["water_leak", "pipe_connection", "gas_connection", "fixture_connection"], { en: "Plumbing contractor for leaks, pipework, water connections, fixture connections, and gas connection review.", fi: "Putkiurakoitsija vuotoihin, putkitöihin, vesiliitäntöihin, kalusteliitäntöihin ja kaasuliitännän tarkastukseen." }),
  company("company_saku_putki", "Saku Putki Service Oy", "plumbing", ["pipe", "drain", "water", "gas connection", "connection"], ["putki", "viemäri", "vesi", "kaasuliitäntä", "liitäntä"], ["Korjaus", "Kuntoon"], ["Quality"], false, ["pipe_connection", "drain_connection", "gas_connection", "fixture_connection"], { en: "Plumbing service for pipe, drain, water, and gas connection related work that needs manual confirmation.", fi: "Putkipalvelu putki-, viemäri-, vesi- ja kaasuliitäntöihin, jotka vaativat käyttäjän varmistuksen." }),
  company("company_northflow_lvi", "NorthFlow LVI Oy", "hvac_ventilation", ["hvac", "ventilation", "air", "radiator", "heating", "valve"], ["lvi", "ilmanvaihto", "patteri", "lämmitys", "venttiili"], ["Korjaus", "Kuntoon"], ["Quality"], true),
  company("company_kitchenfix", "KitchenFix Pro Oy", "kitchen", ["kitchen", "cabinet", "countertop"], ["keittiö", "kaappi", "taso"], ["Kiinnitetään kunnolla", "Korjaus"], ["Quality"], true),
  company("company_kalustekulma", "KalusteKulma Oy", "kitchen", ["fixture", "furniture", "cabinet"], ["kaluste", "kaappi"], ["Kiinnitetään kunnolla", "Kuntoon"]),
  company("company_applianceinstall", "ApplianceInstall Finland Oy", "kitchen", ["appliance", "oven", "dishwasher", "fridge", "refrigerator", "appliance installation"], ["kodinkone", "uuni", "astianpesukone", "jääkaappi"], ["Korjaus", "Kuntoon"], ["Quality"], false, ["appliance_installation", "kitchen_appliance_connection"], { en: "Kitchen appliance installation and connection support for ovens, dishwashers, refrigerators, and similar fixtures.", fi: "Keittiön kodinkoneiden asennus ja liitäntätuki uuneille, astianpesukoneille, jääkaapeille ja vastaaville kalusteille." }),
  company("company_sealpro", "SealPro Finland Oy", "sealing_waterproofing", ["sealant", "seal", "waterproofing"], ["sauma", "tiiviste", "vedeneristys"], ["Kittaus ja maalaus", "Korjaus"], ["Quality"], true),
  company("company_wetroom_shield", "WetRoom Shield Oy", "sealing_waterproofing", ["wet room", "waterproofing", "bathroom seal"], ["märkätila", "vedeneristys", "kylpyhuone"], ["Korjaus", "Kuntoon"]),
  company("company_saumatek", "SaumaTek Oy", "sealing_waterproofing", ["joint", "sealant", "caulk"], ["sauma", "kittaus"], ["Kittaus ja maalaus", "Korjaus"]),
  company("company_nordic_flooring", "Nordic Flooring Oy", "flooring", ["floor", "flooring", "tile"], ["lattia", "laatta"], ["Korjaus", "Hionta"], ["Quality"], true),
  company("company_laattalattia", "LaattaLattia Oy", "flooring", ["tile", "floor tile"], ["laatta", "laattalattia"], ["Korjaus", "Kuntoon"]),
  company("company_floorcare", "FloorCare Rakennus Oy", "flooring", ["scratch", "floor repair"], ["naarmu", "lattiakorjaus"], ["Hionta", "Korjaus"]),
  company("company_maalausmestarit", "MaalausMestarit Oy", "painting_finishing", ["paint", "painting", "wall scratch"], ["maali", "maalaus", "seinänaarmu"], ["Maalataan uudestaan", "Maalataan"], ["Quality"], true),
  company("company_surfacefix", "SurfaceFix Oy", "painting_finishing", ["surface", "scratch", "finish"], ["pinta", "naarmu", "viimeistely"], ["Maalataan", "Korjaus"]),
  company("company_drywall_finish", "Drywall Finish Oy", "painting_finishing", ["drywall", "plaster", "finish"], ["kipsilevy", "tasoite"], ["Kittaus ja maalaus", "Maalataan"]),
  company("company_north_electric", "North Electric Oy", "electrical", ["electrical", "socket", "cable", "safety issue", "power connection", "electrical connection"], ["sähkö", "pistorasia", "kaapeli", "turvallisuus", "sähköliitäntä"], ["Korjaus", "Kuntoon"], ["Safety"], true, ["electrical_connection", "socket", "cable", "power", "electrical_safety"], { en: "Electrical contractor for sockets, cables, power connections, and electrical safety issues.", fi: "Sähköurakoitsija pistorasioihin, kaapeleihin, sähköliitäntöihin ja sähköturvallisuuteen." }),
  company("company_valovirta", "ValoVirta Oy", "electrical", ["light", "lighting", "power"], ["valo", "valaistus", "virta"], ["Korjaus", "Kuntoon"]),
  company("company_socketpro", "SocketPro Service Oy", "electrical", ["socket", "outlet"], ["pistorasia", "rasia"], ["Kiinnitetään kunnolla", "Korjaus"]),
  company("company_palostop", "PaloStop Oy", "fire_stopping_safety", ["fire stop", "fire stopping", "penetration"], ["palokatko", "läpivienti"], ["Korjaus", "Kuntoon"], ["Palokatko", "Safety"], true),
  company("company_cleansite", "CleanSite Oy", "cleaning", ["clean", "debris", "dust"], ["siivous", "roska", "pöly"], ["Kuntoon"], ["Environment"], true),
  company("company_masonry_structural", "Masonry Structural Oy", "masonry_structural", ["masonry", "concrete", "structure"], ["muuraus", "betoni", "rakenne"], ["Korjaus", "Kuntoon"], ["Quality"], true),
  company("company_window_door_service", "Window and Door Service Oy", "doors_windows", ["balcony door", "window", "door seal", "cold air", "does not close", "seal"], ["parvekkeen ovi", "ikkuna", "tiiviste", "kylmää ilmaa", "ei sulkeudu"], ["Korjaus", "Kuntoon"], ["Quality"], true),
  company("company_doorfix_rakennus", "DoorFix Rakennus Oy", "doors_locks", ["entrance door", "door", "lock", "frame", "rubs"], ["ulko-ovi", "ovi", "lukko", "karmi", "hankaa"], ["Korjaus", "Kiinnitetään kunnolla"], ["Quality"], true),
  company("company_ceilingpro", "CeilingPro Oy", "ceiling", ["ceiling", "ceiling panel", "meeting room"], ["katto", "kattopaneeli", "kokoushuone"], ["Kuntoon", "Korjaus"], ["Quality"], true),
  company("company_scaffoldsafe", "ScaffoldSafe Oy", "scaffolding", ["scaffold", "scaffolding", "west facade"], ["teline", "rakennusteline", "länsijulkisivu"], ["Kiinnitetään kunnolla", "Korjaus"], ["Safety"], true),
  company("company_concretecare", "ConcreteCare Oy", "concrete", ["concrete", "parking garage ramp", "crack"], ["betoni", "parkkihallin ramppi", "halkeama"], ["Korjaus", "Kuntoon"], ["Quality"], true),
  company("company_site_logistics", "SiteLogistics Oy", "site_logistics", ["loading area", "delivery", "materials"], ["lastausalue", "toimitus", "materiaalit"], ["Kuntoon"], ["Environment"], true),
  company("company_fall_protection", "FallProtect Site Safety Oy", "fall_protection", ["fall protection", "elevator shaft", "opening", "guardrail"], ["putoamissuojaus", "hissikuilu", "aukko", "kaide"], ["Kiinnitetään kunnolla", "Korjaus"], ["Safety"], true),
] as const;
