import { useRef, useState } from 'react';
import { TranscribeRealtimeOptions, WhisperContext } from './../node_modules/whisper.rn/src/index';
// import { initWhisper } from 'whisper.rn';




// real time transcription with whisper models

import { checkRecordingPermission } from '@/hooks/recordingPermission';
import { ASRResult } from '@/src/engine/types';
import { initWhisper } from 'whisper.rn';


// import { RealtimeTranscriber } from 'whisper.rn/realtime-transcription';
// import { AudioPcmStreamAdapter } from 'whisper.rn/realtime-transcription/adapters';
// import { RealtimeTranscriber } from 'whisper.rn/src/realtime-transcription';
// import AudioPcmStreamAdapter from '@fugood/react-native-audio-pcm-stream';

// import { RealtimeTranscriber } from 'whisper.rn/src/realtime-transcription'
// import { AudioPcmStreamAdapter } from 'whisper.rn/src/realtime-transcription/adapters'





// Hallucination filters to ignore common phantom phrases generated by Whisper during silence.
const HALLUCINATION_FILTERS = [
  '[silence]', '[blank]', '(silence)', '(blank)', '[no speech]', '(no speech)',
  '[noise]', '(noise)', 'Thanks for watching', 'Thank you', 'Subscribe'
];

export const useWhisperEngine = () => {

  const [whisperInitialized, setWhisperInitialized] = useState<WhisperContext | null>(null);
   const stopRef = useRef<null | (() => Promise<void> | void)>(null); 

  const initWhisperModel = async (modelName: string): Promise<void> => {
    const assets: Record<string, any> = {
      'tiny.en': require('../assets/whisper/ggml-tiny.en.bin'),
      'tiny': require('../assets/whisper/ggml-tiny.bin'),
      'base.en': require('../assets/whisper/ggml-base.en.bin'),
      'base': require('../assets/whisper/ggml-base.bin'),
    };
    console.log("Initializing Whisper model:", modelName);
    const modelAsset = assets[modelName];

    const whisperContext = await initWhisper({
      filePath: modelAsset,
    });
    console.log("Whisper initialized with model:", whisperContext);
    setWhisperInitialized(whisperContext);
  }

  const whisperStart = async (
    onResult: (result: ASRResult) => void,
    onError: (err: Error) => void,
    audioUri?: string,

  ): Promise<void> => {

    // const whisperContext = await initWhisperModel(modelName);
    if (!whisperInitialized) throw new Error("Whisper not initialized");

    const language = 'en';

    if (audioUri) {
      try {
        const { promise } = whisperInitialized.transcribe(audioUri, {
          language,
        });
        const res = await promise;
        onResult({ text: res.result || '', isFinal: true });
      } catch (err) {
        onError(err as Error);
      }
    } else {
      try {

        // crearting audio stream from mic and feeding it to whisper in real time
        const hasPermission = await checkRecordingPermission();
        if (!hasPermission) {
          onError(new Error("Microphone permission is required."));
          return;
        }

        // const audioStream = new AudioPcmStreamAdapter();

        const transciberOptions: TranscribeRealtimeOptions = {
          language,
          realtimeAudioSec: 300,
          realtimeAudioSliceSec: 20,
          realtimeAudioMinSec: 2,
          audioSessionOnStartIos: {
            category: 'PlayAndRecord' as any,
            options: ['MixWithOthers'] as any,
            mode: 'default' as any,
          },
          audioSessionOnStopIos: 'restore' as any,

        }

        const { subscribe, stop } = await whisperInitialized.transcribeRealtime(transciberOptions);

        stopRef.current = stop;

        subscribe((evt: any) => {

          // const {data, processT}= evt || {};
          const text = evt.data?.result || '';
          console.log("Whisper ASR Event:", evt);

          const isHallucination = HALLUCINATION_FILTERS.some(f => text.includes(f));

          if (text && !isHallucination) {
            console.log("Whisper ASR Result:", text);
            onResult({ text, isFinal: !evt.isCapturing === false });
          }

          // stop();
        });
      } catch (err) {
        onError(err as Error);
      }
    }
  }

   const stopWhisper = async () => {
    if (stopRef.current) {
      await stopRef.current();
      stopRef.current = null;
    }
  };


  return {
    init: initWhisperModel,
    start: whisperStart,
    stop: stopWhisper,
  }
}


// const transcriber = new RealtimeTranscriber({
//   whisperContext: this.whisperContext,
//   // audioStream,
//   // language,
//   // fs:RNFS
// },
//   {
//     audioSliceSec: 30,
//     audioMinSec: 1,
//     maxSlicesInMemory: 3,
//     transcribeOptions: { language: language },
//   },
//   //callback functions for transcriber events
//   {
//     onTranscribe: (event:any) => {
//       console.log('Transcription:', event.data?.result);
//       // onResult({ text: event.data?.result, isFinal: event.data.isFinal === false });
//     },
//     // onVad: (event) => {
//     //   console.log('VAD:', event.type, event.confidence)
//     // },
//     onError: (error:any) => {
//       console.error('Error:', error)
//     }

//   }
// )

//   await transcriber.start()

// const { stop, subscribe } = await this.whisperContext.transcribeRealtime({
//   language,
//   realtimeAudioSec: 30,

// });
// this.stopper = stop;

// subscribe((evt: any) => {
//   const text = evt.data?.result || '';
//   console.log("Whisper ASR Event:", evt);

//   const isHallucination = HALLUCINATION_FILTERS.some(f => text.includes(f));

//   if (text && !isHallucination) {
//     onResult({ text, isFinal: evt.isCapturing === false });
//   }
// });
//     } catch (err) {
//       onError(err as Error);
//     }
//   }
// }

// async stop(): Promise<void> {
//   if (this.stopper) {
//     await this.stopper();
//     this.stopper = null;
//   }
// }

// async destroy(): Promise<void> {
//   await this.stop();
//   if (this.whisperContext) {
//     await this.whisperContext.release();
//     this.whisperContext = null;
//   }
// }
// }
